#!/usr/bin/env node

/**
 * Script to update frontend/.env with deployed contract addresses
 * 
 * Usage:
 *   node scripts/update-env.js
 *   node scripts/update-env.js --hub 0x... --om 0x... --mnee 0x... --faucet 0x...
 */

import { readFileSync, writeFileSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const rootDir = join(__dirname, "..");
const envPath = join(rootDir, "frontend", ".env");

// Get addresses from command line arguments
function getAddresses() {
  const args = process.argv.slice(2);
  const addresses = {
    hub: null,
    om: null,
    mnee: null,
    faucet: null,
  };

  // Parse command line arguments
  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--hub" && args[i + 1]) {
      addresses.hub = args[i + 1];
      i++;
    } else if (args[i] === "--om" && args[i + 1]) {
      addresses.om = args[i + 1];
      i++;
    } else if (args[i] === "--mnee" && args[i + 1]) {
      addresses.mnee = args[i + 1];
      i++;
    } else if (args[i] === "--faucet" && args[i + 1]) {
      addresses.faucet = args[i + 1];
      i++;
    }
  }

  return addresses;
}

function updateEnvFile(addresses) {
  let envContent = "";

  // Read existing .env if it exists
  if (existsSync(envPath)) {
    envContent = readFileSync(envPath, "utf-8");
  }

  // Parse existing env variables
  const envVars = new Map();
  const lines = envContent.split("\n");
  
  lines.forEach((line) => {
    const trimmed = line.trim();
    // Keep comments and empty lines
    if (trimmed.startsWith("#") || trimmed === "") {
      return;
    }
    // Parse key=value pairs
    const equalIndex = trimmed.indexOf("=");
    if (equalIndex > 0) {
      const key = trimmed.substring(0, equalIndex).trim();
      const value = trimmed.substring(equalIndex + 1).trim();
      envVars.set(key, value);
    }
  });

  // Update or add addresses
  if (addresses.hub) {
    envVars.set("VITE_HUB_ADDRESS", addresses.hub);
  }
  if (addresses.om) {
    envVars.set("VITE_OM_TOKEN_ADDRESS", addresses.om);
  }
  if (addresses.mnee) {
    envVars.set("VITE_MNEE_ADDRESS", addresses.mnee);
  }
  if (addresses.faucet) {
    envVars.set("VITE_FAUCET_ADDRESS", addresses.faucet);
  }

  // Build new .env content
  const header = `# QUIPO Protocol Contract Addresses
# Auto-generated by update-env.js
# Last updated: ${new Date().toISOString()}

`;
  
  // Sort variables alphabetically for consistency
  const sortedVars = Array.from(envVars.entries()).sort((a, b) => 
    a[0].localeCompare(b[0])
  );
  
  const envLines = sortedVars
    .map(([key, value]) => `${key}=${value}`)
    .join("\n");

  const newEnvContent = header + envLines + "\n";

  // Write to file
  writeFileSync(envPath, newEnvContent, "utf-8");
  
  return envVars;
}

function main() {
  console.log("🔧 Updating frontend/.env with contract addresses");
  console.log("=".repeat(60));
  
  const addresses = getAddresses();
  
  // Check if any addresses were provided
  const hasAddresses = Object.values(addresses).some(addr => addr !== null);
  
  if (!hasAddresses) {
    console.error("❌ No addresses provided.");
    console.log("\n💡 Usage:");
    console.log("   node scripts/update-env.js --hub 0x... --om 0x... [--mnee 0x...] [--faucet 0x...]");
    console.log("\n📋 Example:");
    console.log("   node scripts/update-env.js --hub 0x1234... --om 0x5678... --mnee 0x9abc... --faucet 0xdef0...");
    process.exit(1);
  }

  console.log("\n📝 Contract Addresses:");
  if (addresses.hub) {
    console.log(`   QUIPO Hub:    ${addresses.hub}`);
  }
  if (addresses.om) {
    console.log(`   omMNEE Token: ${addresses.om}`);
  }
  if (addresses.mnee) {
    console.log(`   MNEE Token:   ${addresses.mnee}`);
  }
  if (addresses.faucet) {
    console.log(`   Faucet:       ${addresses.faucet}`);
  }

  const updatedVars = updateEnvFile(addresses);
  
  console.log("\n✅ Successfully updated frontend/.env");
  console.log("\n📋 Updated variables:");
  if (addresses.hub) {
    console.log(`   VITE_HUB_ADDRESS=${updatedVars.get("VITE_HUB_ADDRESS")}`);
  }
  if (addresses.om) {
    console.log(`   VITE_OM_TOKEN_ADDRESS=${updatedVars.get("VITE_OM_TOKEN_ADDRESS")}`);
  }
  if (addresses.mnee) {
    console.log(`   VITE_MNEE_ADDRESS=${updatedVars.get("VITE_MNEE_ADDRESS")}`);
  }
  if (addresses.faucet) {
    console.log(`   VITE_FAUCET_ADDRESS=${updatedVars.get("VITE_FAUCET_ADDRESS")}`);
  }
  
  console.log("\n💡 Next steps:");
  console.log("   1. Restart your dev server: npm run dev");
  console.log("   2. The frontend will now use these addresses");
  console.log("\n" + "=".repeat(60));
}

main();







